version: 0.2

env:
  shell: bash
  parameter-store:
    DEPENDENCY_CHECK_S3_BUCKET: /config/dependency-check/bucket-name
  variables:
    LANG: C.UTF-8
    DEPENDENCY_CHECK_VERSION: 7.4.4

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt-get update
      - apt-get install -y unzip wget
      - mkdir -p /opt/dependency-check
      - wget -q https://github.com/jeremylong/DependencyCheck/releases/download/v${DEPENDENCY_CHECK_VERSION}/dependency-check-${DEPENDENCY_CHECK_VERSION}-release.zip
      - unzip -q dependency-check-${DEPENDENCY_CHECK_VERSION}-release.zip -d /opt/
      - chmod -R +x /opt/dependency-check/bin
      - export PATH=$PATH:/opt/dependency-check/bin
  
  pre_build:
    commands:
      - echo "Preparing for vulnerability check"
  
  build:
    commands:
      - echo "Running vulnerability scan..."
      - /opt/dependency-check/bin/dependency-check.sh --scan . --project ${SERVICE_NAME} --enableExperimental --disableAssembly --disableYarnAudit --disablePnpmAudit --out ./dependency-check-report
      
      # Upload vulnerability information to S3
      - echo "Uploading vulnerability report"
      - |
        if [ -d "./dependency-check-report" ]; then
          aws s3 cp ./dependency-check-report s3://${DEPENDENCY_CHECK_S3_BUCKET}/${SERVICE_NAME}/ --recursive
        else
          echo "Warning: Vulnerability report directory not found"
        fi
  
  post_build:
    commands:
      - echo "Vulnerability check completed on $(date)"

cache:
  paths:
    - '/opt/dependency-check/**/*'